# -*- coding: utf-8 -*-
"""
/***************************************************************************
 Appl_idrologica
                                 A QGIS plugin
 Appl_idrologica
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2021-11-11
        copyright            : (C) 2021 by annagrass
        email                : anangrass@gmail.com
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""

__author__ = 'annagrass'
__date__ = '2021-11-11'
__copyright__ = '(C) 2021 by annagrass'


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load Appl_idrologica class from file Appl_idrologica.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .Appl_idrologica import Appl_idrologicaPlugin
    return Appl_idrologicaPlugin()
